// Writes src/tools/fonts.gen.ts (the fonts buni offers) and src/tools/fontdata.gen.ts (their files, embedded so
// every export and render has them).
// Run after changing the font packages: bun scripts/fonts.ts
import { join } from "node:path";

const root = join(import.meta.dir, "..");
// A small, distinct set across sans, serif, display and mono, all variable (100–900) and open-licensed. The
// typography skill lists the same families; a test keeps them in step.
const FAMILIES = [
  "Manrope", "Inter", "Bricolage Grotesque", "DM Sans", "Space Grotesk", "Instrument Sans", "Plus Jakarta Sans", "Schibsted Grotesk", "Figtree",
  "Fraunces", "Newsreader", "Source Serif 4", "Playfair Display", "EB Garamond",
  "Unbounded", "Syne", "JetBrains Mono",
];
const FONTS = FAMILIES.map((family) => {
  const slug = family.toLowerCase().replace(/ /g, "-");
  return { family, file: `node_modules/@fontsource-variable/${slug}/files/${slug}-latin-wght-normal.woff2` };
});
const data = await Promise.all(
  FONTS.map(async (f) => `  ${JSON.stringify(f.family)}: ${JSON.stringify(Buffer.from(await Bun.file(join(root, f.file)).arrayBuffer()).toString("base64"))},`),
);
// The names are needed everywhere; the files (about 850 KB) only where a design leaves buni, so they're apart.
await Bun.write(
  join(root, "src/tools/fonts.gen.ts"),
  `// Generated by scripts/fonts.ts; do not edit.\nexport const FONT_FAMILIES: readonly string[] = ${JSON.stringify(FAMILIES)};\n`,
);
await Bun.write(
  join(root, "src/tools/fontdata.gen.ts"),
  `// Generated by scripts/fonts.ts; do not edit.\nexport const FONT_DATA: Readonly<Record<string, string>> = {\n${data.join("\n")}\n};\n`,
);
// The fonts travel inside buni, so their licenses (the SIL Open Font License) travel with them.
const notices = await Promise.all(
  FAMILIES.map(async (family) => {
    const slug = family.toLowerCase().replace(/ /g, "-");
    return `## ${family}\n\n\`\`\`\n${(await Bun.file(join(root, `node_modules/@fontsource-variable/${slug}/LICENSE`)).text()).trim()}\n\`\`\`\n`;
  }),
);
await Bun.write(
  join(root, "FONT-LICENSES.md"),
  `# Font licenses\n\nbuni embeds these fonts (src/tools/fontdata.gen.ts, from [Fontsource](https://fontsource.org)) so designs draw the\nsame everywhere. Each is used under its own license, reproduced below.\n\n${notices.join("\n")}`,
);
