// Writes the Homebrew formula for a release: bun scripts/formula.ts <version> <checksums.txt>
// checksums.txt is sha256sum's output for the release's tarballs and bottles (scripts/bottles.ts).
//
// The formula ships bottles: Homebrew pours a bottle as it is, while a formula without one counts as built from
// source and refuses to install when the Command Line Tools are out of date, even though nothing is compiled.

/** Each release platform: its tarball's name and the Homebrew bottle tag it is poured on. A macOS bottle is used
 * on that version and every newer one, so the oldest supported version covers them all. */
export const PLATFORMS = [
  { os: "darwin", arch: "arm64", tag: "arm64_sonoma" },
  { os: "darwin", arch: "x64", tag: "sonoma" },
  { os: "linux", arch: "arm64", tag: "arm64_linux" },
  { os: "linux", arch: "x64", tag: "x86_64_linux" },
] as const;

type Platform = (typeof PLATFORMS)[number];
export const tarball = (version: string, p: Platform) => `buni-${version}-${p.os}-${p.arch}.tar.gz`;
/** The name Homebrew asks a bottle root_url for: name-version.tag.bottle.tar.gz. */
export const bottle = (version: string, p: Platform) => `buni-${version}.${p.tag}.bottle.tar.gz`;

export function formula(version: string, sums: string): string {
  const sha = new Map(sums.trim().split("\n").map((l) => {
    const [hash = "", name = ""] = l.trim().split(/\s+\*?/);
    return [name, hash] as const;
  }));
  const hash = (name: string) => {
    const h = sha.get(name);
    if (!h) throw new Error(`no checksum for ${name}`);
    return h;
  };
  const at = (os: Platform["os"], arch: Platform["arch"]) => {
    const p = PLATFORMS.find((x) => x.os === os && x.arch === arch);
    if (!p) throw new Error(`no platform ${os}-${arch}`);
    const name = tarball(version, p);
    return `      url "https://github.com/emusoi/buni/releases/download/v${version}/${name}"\n      sha256 "${hash(name)}"`;
  };
  const bottles = PLATFORMS.map((p) => `    sha256 cellar: :any_skip_relocation, ${p.tag}: "${hash(bottle(version, p))}"`).join("\n");

  return `# Generated by scripts/formula.ts in github.com/emusoi/buni for each release; do not edit by hand.
class Buni < Formula
  desc "Design tools for agents and people: the .buni format, CLI, MCP and a live viewer"
  homepage "https://github.com/emusoi/buni"
  version "${version}"
  license "Apache-2.0"

  bottle do
    root_url "https://github.com/emusoi/buni/releases/download/v${version}"
${bottles}
  end

  on_macos do
    on_arm do
${at("darwin", "arm64")}
    end
    on_intel do
${at("darwin", "x64")}
    end
  end

  on_linux do
    on_arm do
${at("linux", "arm64")}
    end
    on_intel do
${at("linux", "x64")}
    end
  end

  def install
    bin.install "buni"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/buni --version")
  end
end
`;
}

if (import.meta.main) {
  const [version, sums] = process.argv.slice(2);
  if (!version || !sums) throw new Error("usage: bun scripts/formula.ts <version> <checksums.txt>");
  process.stdout.write(formula(version, await Bun.file(sums).text()));
}
