// Generated by scripts/fonts.ts; do not edit.
export const FONT_FAMILIES: readonly string[] = ["Manrope","Inter","Bricolage Grotesque","DM Sans","Space Grotesk","Instrument Sans","Plus Jakarta Sans","Schibsted Grotesk","Figtree","Fraunces","Newsreader","Source Serif 4","Playfair Display","EB Garamond","Unbounded","Syne","JetBrains Mono"];
